title: Jonathan DelGizzi # your name (or website title) here
logo: "/images/Self.jfif?raw=true" # your photo (or logo) here
description:
jdelgizzi@comcast.net
<br><br>
3 Bittersweet Lane
<br><br>
Weston MA, 02493
 <a href="https://www.linkedin.com/in/jonathan-delgizzi-177483108/">Resume</a> 
theme: jekyll-theme-Minimal
