title: Jonathan DelGizzi # your name (or website title) here
logo: "/images/Self.jfif?raw=true" # your photo (or logo) here
description: >
  <a href="https://www.linkedin.com/in/jonathan-delgizzi-177483108/">Resume</a> 
  <br><br>
  Address: 3 Bittersweet Lane, Weston MA, 02493
  <br><br>
  Email: jdelgizzi@comcast.net
theme: jekyll-theme-Minimal
