title: Jonathan DelGizzi # your name (or website title) here
logo: "/images/Self.jfif?raw=true" # your photo (or logo) here

<a href="https://www.linkedin.com/in/jonathan-delgizzi-177483108/">Resume</a> 
"Email: jdelgizzi@comcast.net"
<Br><Br>
"Address:3 Bittersweet Lane Weston MA, 02493"

theme: jekyll-theme-Minimal

