title: Jonathan DelGizzi # your name (or website title) here
logo: "/images/Self.jfif?raw=true" # your photo (or logo) here

<a href="https://www.linkedin.com/in/jonathan-delgizzi-177483108/">Resume</a> 


theme: jekyll-theme-Minimal

